# Generated by Django 3.1 on 2020-08-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('company_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Codal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('filename', models.CharField(max_length=128)),
                ('publish_date_time', models.DateTimeField()),
                ('fund', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('forosh', models.CharField(max_length=128)),
                ('sood_amaliyati', models.CharField(max_length=128)),
                ('sood_khales', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=128)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.symbol')),
            ],
        ),
    ]
