# Generated by Django 3.0.8 on 2020-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=128)),
                ('filename', models.CharField(max_length=128)),
                ('publish_date_time', models.DateTimeField()),
            ],
        ),
    ]
